export const INCREMENT = 'INCREMENT';
export const CHANGE_DATE = 'CHANGE_DATE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const FILTER_DATE_ARTICLE = 'FILTER_DATE_ARTICLE';
export  const FILTER_SELECTED = 'FILTER_SELECTED';
export const SELECTED_ARTICLE = 'SELECTED_ARTICLE';